

services:
  price-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-price-scraper
    environment:
      - TZ=UTC
    # Mount volume for log persistence
    volumes:
      - ./logs:/app/logs
    restart: "no"
